'use client';

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import { Inter } from "next/font/google";
import DarkModeToggle from "@/components/mode/DarkModeToggle";
import { SessionProvider } from "next-auth/react"; // ✅ Import this

// google font
const inter = Inter({
  subsets:["latin"],
  display: "swap",
});

// FONT 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// FONT 
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// META DATA ( FOR ANYONE TO USE TO SEARCH BY KEYWORD )
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionProvider> {/* ✅ Wrap with SessionProvider */}
          {/* <DarkModeToggle/> */}
          <Sidebar>{children}</Sidebar>
        </SessionProvider>
      </body>
    </html>
  );
}
